### PR TITLE
support multiple names for one cert and select authenticator based on variable

### PR DESCRIPTION
**Pull request by rngadam**
fixes:

* missing hostname parameter (-d)
* uses a list of hosts instead of just the first host
* selects between web authenticator and standalone based on the variable being present or not

### CODE REVIEW

**Comment by thefinn93** [comment]
the first two are not broken, they are that way intentionally:

`-d` is just specified in [{{ letsencrypt_command }}](https://github.com/thefinn93/ansible-letsencrypt/blob/e7cd4a74f56e6dc58cbac9926494f018fdab3c2d/defaults/main.yml#L9) using a for loop, which works in a way that is more friendly for the rate limits (i believe are currently 5 certs per week per second level domain or something). By requesting multiple names for one cert instThis is

**Comment by thefinn93** [comment]
shit I accidently hit the close button... :/

**Comment by thefinn93** [comment]
[More info on the rate limiting stuff](https://community.letsencrypt.org/t/public-beta-rate-limits/4772/3).

**Comment by rngadam** [comment]
modified to work both nicely with the rate limit and the authenticator selection

also made the virtualenv install for Debian only (fails on Ubuntu)

**Comment by thefinn93** [comment]
If Ubuntu doesn't have the package names of Debian, than Ubuntu should get a special case. Also, it should be a separate pull request. Once again, the multiple domain thing is handled in [`defaults.yml`](https://github.com/thefinn93/ansible-letsencrypt/blob/feaabf55a7517629b095df932f2587952003a0af/defaults/main.yml#L9), which builds them into `letsencrypt_command`. Please make one pull request per change so they can each be discussed individually.

**Comment by thefinn93** [comment]
Can I assume this should be closed in favor of #8?

**Comment by rngadam** [comment]
sure

**Pull request closed without merging**
