### PR TITLE
use the certbot package from jessie-backports on debian

### PR DESCRIPTION
**Pull request by ArcolaJasper**
only tested with Debian Jessie, but does get certs etc for me.

### CODE REVIEW

**Comment by rfleschenberg** [comment]
Merging https://github.com/ArcolaJasper/ansible-letsencrypt/pull/1 should update this PR so that Debian Stretch is supported. I ran a quick test against a fresh Stretch box.

**Comment by thefinn93** [comment]
```yaml
  - name: check for Debian != jessie
    fail:
      msg: "Only the jessie release of Debian is supported at the moment"
when: ansible_distribution == "Debian" and ansible_distribution_release != "jessie"
```

Perhaps we could not refuse to run on non-jessie versions of Debian? Jessie isn't even the stable version anymore. Maybe just run the notdebian.yml in that case

**Comment by ArcolaJasper** [comment]
Ah, sorry, I miss read the PR from @rfleschenberg as being against thefinn93/ansible-letsencrypt rather than my copy. Let me just check it and merge it and then update this PR.

**Comment by ArcolaJasper** [comment]
Ok, That add stretch support and will fall back to using pip on non-debian systems.

**Comment by thefinn93** [comment]
Cool, looks good, thanks!

**Pull request merged**
