### PR TITLE
Short fixes, cleanup

### PR DESCRIPTION
**Pull request by merqlove**
Fixed previous PR's.
Tested on Ubuntu trusty. Nginx 1.4.6
Debian part is the same as in original.

### CODE REVIEW

**Comment by thefinn93** [comment]
Okay, same things I asked about the other PR: `letsencrypt_command` already has the domain arguments. Why are you adding them again (but only in the Ubuntu one?)

They should be as similar as possible, and only do the things that require differences (which appears to be just the package name of virtualenv)

**Comment by merqlove** [comment]
@thefinn93, Ok, just reviewed merged commits. I think it will work as is. Just changed installed to present. 
Also special apt for Debian is required. Ubuntu trusty don't have 'virtualenv' package.

**Comment by thefinn93** [comment]
Ah, much better! I'm tempted to merge now, but it appears that Ubuntu 16.04 [has the virtualenv package](http://packages.ubuntu.com/xenial/virtualenv), while it is only available in [jessie, strech and sid](https://packages.debian.org/search?keywords=virtualenv) in Debian. Perhaps the conditional for installing it should be somewhat more elaborate...

**Comment by merqlove** [comment]
We can compare release number as workaround.

**Comment by thefinn93** [comment]
Yeah. Would you like to do so before I merge this?

**Comment by merqlove** [comment]
Am, i will have time for it only tomorrow...Also if you have 16.04 you can merge, add some code & test faster then me :+1:

**Comment by thefinn93** [comment]
I do not Ubuntu installed on any of my servers

**Comment by merqlove** [comment]
14.04 trusty is current major LTS release. 16.04 will be released at 04.16.
So we can stop on trusty for now :)
I have tested current yaml on trusty.

--
Best regards,
Alexander Merkulov

E-mail: sasha@merqlove.ru
Tel.:  +7(925) 278-44-98
Skype:  merqlove

**Comment by thefinn93** [comment]
The other thing to bear in mind is that Ubuntu 16.04 has [a letsencrypt package](http://packages.ubuntu.com/xenial/letsencrypt), as does [Debian](https://packages.debian.org/sid/letsencrypt) for sid and stretch, so maybe the install procedure should be pretty different on those Distros

**Comment by merqlove** [comment]
Yeah, last steps may change. Anyway we will need test on those systems if we want to have its support :)

**Comment by thefinn93** [comment]
True. I guess I'll accept this and open a bug

**Comment by thefinn93** [comment]
Thanks for working on this!

**Comment by merqlove** [comment]
Cheers :+1:

**Pull request merged**
