### PR TITLE
allow renew command args

### PR DESCRIPTION
**Pull request by ryanpineo**
for example, restart a web server after renewal using hooks.
See https://github.com/letsencrypt/letsencrypt/pull/2729/files

### CODE REVIEW

**Comment by thefinn93** [comment]
omg hooks are a thing!? That's awesome, been waiting for that one for quite some time. Could you add a bit to the README about the new variable, maybe with an example for a common use case (eg reload nginx)? After that I'd be happy to merge

**Comment by thefinn93** [comment]
Actually, went and read through the thing a bit more. I feel like it might be more appropriate to break it into 3 variables, to allow separately setting the pre, post and renew hooks. What do you think?

**Comment by ryanpineo** [comment]
My reasoning for just using an argument variable instead of 1 for each hook was just because it was easier and didn't seem to take anything away.  Also puts less of a maintenance burden on this project if any other arguments are added in the future.

Will also add some docs to the README

**Comment by ryanpineo** [comment]
I can also change the variable in to 3 variables, 1 for each hook, if you think that would be nicer.

**Comment by thefinn93** [comment]
Meh that works.

**Comment by ryanpineo** [comment]
haha alright, cheers :)

**Pull request merged**
